# Generated by Django 4.0.10 on 2025-11-22 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenWithExpiry',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 11, 29, 7, 7, 40, 129049, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'Token with Expiry',
                'verbose_name_plural': 'Tokens with Expiry',
            },
            bases=('authtoken.token',),
        ),
    ]
