# Generated by Django 4.0.10 on 2025-11-22 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenwithexpiry',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 29, 7, 34, 52, 318229, tzinfo=utc)),
        ),
    ]
