# Generated by Django 4.0.10 on 2025-11-24 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tokenwithexpiry_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenwithexpiry',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 6, 9, 31, 268643, tzinfo=utc)),
        ),
    ]
